### ISSUE TITLE
Error: 'MeteologgerStorage_simple' object has no attribute '_sorted_files'

### ISSUE THREAD

**Issue by aptiko** [openmeteo/loggertodb#22]
```
Starting loggertodb, 2019-10-28T09:24:23.127487
Reading data storage newer than 2019-10-28T10:50:00
Parsing line '28/10/2019,10:50:00,7.14,195.0,73.5,20.9,0.0,516.1,0.0,*,22.44,30.33,*,17.4,18.5,0
'
Timestamp: 2019-10-28T10:50:00
0 new lines
Reading data storage newer than 2019-10-27T01:50:00
Parsing line '28/10/2019,11:10:00,16.9,16.0,17.9,512.1,7.14,22.0,0.0,71.6,329.1,0.0,19.56,23.34,15.35
'
Timestamp: 2019-10-28T11:10:00
Parsing line '28/10/2019,11:00:00,16.9,16.0,18.0,498.4,7.14,21.6,0.0,74.6,9.5,0.0,19.58,23.36,15.39
'
Timestamp: 2019-10-28T11:00:00
Parsing line '28/10/2019,10:50:00,16.9,16.0,18.0,487.0,7.14,21.3,0.0,78.5,342.3,0.0,19.56,23.36,15.41
'

[...]

Timestamp: 2019-10-27T16:10:00
Parsing line '27/10/2019,16:00:00,17.7,18.1,18.1,199.7,7.14,24.6,0.0,71.2,285.4,0.0,19.62,23.36,15.41
'
Timestamp: 2019-10-27T03:00:00
Parsing line '27/10/2019,02:50:00,17.9,17.0,18.6,1.3,6.75,11.0,0.0,93.1,48.9,0.0,20.15,23.90,15.81
'
Timestamp: 2019-10-27T01:50:00
200 new lines
First new date: 2019-10-27T03:00:00
'MeteologgerStorage_simple' object has no attribute '_sorted_files'
Traceback (most recent call last):
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/cli.py", line 77, in main
    update_database(client, meteologger_storage)
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/cli.py", line 99, in update_database
    new_data = meteologger_storage.get_recent_data(ts_id, ts_end_date)
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/meteologgerstorage.py", line 56, in get_recent_data
    self._check_monotonic(self._cached_data[ts_id].index)
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/meteologgerstorage.py", line 63, in _check_monotonic
    self._raise_monotonic_exception(index)
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/meteologgerstorage.py", line 319, in _raise_monotonic_exception
    self._check_file_order()
  File "/opt/loggertodb-venv/lib/python3.5/site-packages/loggertodb/meteologgerstorage.py", line 324, in _check_file_order
    for file in self._sorted_files:
AttributeError: 'MeteologgerStorage_simple' object has no attribute '_sorted_files'
```

**Comment by aptiko** [comment]
Because of the time change from DST, the hour 03:00 to 04:00 appears twice. Loggertodb then concludes that the data is not monotonic and attempts to raise a "Data is incorrectly ordered" exception. However, because of the changes introduced in 05960dd, it crashes instead.
